OTMS/Controllers/BidderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OTMS.Models;
using System.Net;
namespace OTMS.Controllers
{
    public class BidderController : Controller
    {
        //
        // GET: /Bidder/
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult BidDashboard() //   View with all basic controllers for bidders
        {
            if (Session["isOrg"] != null)
            {
                if (!(bool)Session["isOrg"]) //  if bidder
                {
                    List<TenderNoticeModel> Tenders = DBContext.GetInstance().findTenders("userName", (String)Session["userName"]);
                    ViewData["tenders"] = Tenders;
                    ViewData["empty"] = "false";
                    ViewData["notifications"] = DBContext.GetInstance().findNotificationsOfUser((String)Session["userName"]);
                    if (Tenders.Count == 0) { ViewData["empty"] = true; }
                    return View();   
                }
                else
                {// if org
                    return null; 
                }
            }
            return null;
        }
        public ActionResult Bidderlogin() //    Bidder is logging to the system  
        {
            if (Session["isOrg"] != null)
            {
                if ((bool)Session["isOrg"]) //  if company trying to enter bidders area
                {
                    return RedirectToAction("OrgDashboard", "Organization");    //  redirect to company dashboard
                }
                else
                {
                    return RedirectToAction("BidDashboard", "Bidder");  //  already logged in so redirect
                }
            }

            if (Request.HttpMethod.Equals("POST"))
            {
                BidderModel existing;
                try
                {
                    existing = DBContext.GetInstance().FindOneInBidder("username", Request.Form["username"]);
                    char[] temp = null;

                    temp = existing.password.ToCharArray();
                    for (int i = 0; i < temp.Length; i++)
                    {
                        temp[i] = (char)((int)Convert.ToChar(temp[i]) - 5);   // ReHash Function
                    }
                    String tem = new String(temp);
                    if (existing != null && tem.Equals(Request.Form["password"]))
                    {
                        Session["user"] = existing.Name;                //  creating a new session for recognizing users
                        Session["username"] = existing.userName;
                        Session["isOrg"] = false;                       //  identify user type
                        Session["profilePic"] = existing.ProfilePic;
                        ViewData["message"] = "successfull";            //  error hadling messages
                        return RedirectToAction("BidDashboard", "Bidder");
                    }
                    else
                    {
                        ViewData["errorMsg"] = "Username or Password not match";
                        return View();
                        //  error handling
                    }
                }
                catch { ViewData["errorMsg"] = "Username or Password not match"; }
            }
            return View();
        }
	}
}

OTMS/Controllers/NotificationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OTMS.Models;
namespace OTMS.Controllers
{
    public class NotificationController : Controller
    {
        //
        // GET: /Notification/
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult CreateType1Notification(String tenderID)    // notification type 1 - "new inquiry about tender notice"
        {
            NotificationModel noti = new NotificationModel();
            noti.NoticeId = int.Parse(tenderID);
            noti.Organization = DBContext.GetInstance().getOrganizationOfNotice(tenderID);
            DBContext.GetInstance().createNotificationType1(noti);  //  create db entry
            return Json(null, JsonRequestBehavior.AllowGet);    // enable ajax request.
        }

        public ActionResult CreateType2Notification(String tenderID,String user)
        {                                                       //  notification type 2 - "your inquiry is now answered"
            NotificationModel noti = new NotificationModel();
            noti.NoticeId = int.Parse(tenderID);
            noti.User = user;
            DBContext.GetInstance().createNotificationType2(noti);
            return Json(null, JsonRequestBehavior.AllowGet);    //  enable ajax
        }
        public ActionResult CreateType3Notification(String tenderID,String bidder)
        {                                            //  notification type 2 - "congratulations, your bid is selected as winning bid"
            NotificationModel noti = new NotificationModel();
            noti.NoticeId = int.Parse(tenderID);
            noti.User = bidder; 
            DBContext.GetInstance().createNotificationType3(noti);
            return Json(null, JsonRequestBehavior.AllowGet);    //  enable ajax
        }

        public ActionResult caughtNotification(String notificationID)
        {                                           //  set notification as caught, so it would not be notified again 
            DBContext.GetInstance().caughtNotification(notificationID);
            return Json(null, JsonRequestBehavior.AllowGet);
        }

	}
}

OTMS/Controllers/TenderController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OTMS.Models;
namespace OTMS.Controllers
{
    public class TenderController : Controller
    {
        //
        // GET: /Tender/
        public ActionResult Index()
        {
            return View();
        }
        public FileResult Download(String bidId)    //  donload a tender PDF
        {
            string contentType = "application/pdf";
            return File(DBContext.GetInstance().getBidPdf(bidId), contentType); //  return file result
        }
        public ActionResult tenderDetails(String tenderID)  //  take details of the tender given tender ID
        {
            if (Session["isOrg"] != null)   //  if not in a session 
            {
                if ((bool)Session["isOrg"]) //  If Org session
                {
                    List<TenderNoticeModel> tenderlist = DBContext.GetInstance().findTendersOfOrg("noticeid", tenderID);    //tender
                    List<BiddersOfNotice> bidders = DBContext.GetInstance().FindBiddersOfTender(tenderID);  // bids for that tender
                    List<InquiryModel> inqList = DBContext.GetInstance().FindAllInquiries(tenderID);    //  inquiries about tender
                    ViewData["tender"] = tenderlist.First();
                    ViewData["Bidders"] = bidders;
                    ViewData["inqList"] = inqList;
                    return View();
                }
            }
            return null;     
        }
        public FileStreamResult getPDFofNotice(String noticeID) //  given tender id return its PDF
        {   
            Response.Clear();
            MemoryStream ms = new MemoryStream(DBContext.GetInstance().findTenderPDF(noticeID));    //  PDF as a filestream
            Response.ContentType = "application/pdf";
            Response.Buffer = true;
            ms.WriteTo(Response.OutputStream);
            Response.End();
            return new FileStreamResult(ms, "application/pdf"); //  return PDF as a filestream
        }

        public ActionResult addNewInquiry(String noticeId,String Question)  //  ask a question about tender
        {
            InquiryModel inq = new InquiryModel
            {
                NoticeId = int.Parse(noticeId),
                Question = Question,
                User = (String)Session["username"],
                Answered = false
            };
            DBContext.GetInstance().createInquiry(inq); //  create DB 
            return Json(null, JsonRequestBehavior.AllowGet);    //  allow ajax
        }
        public ActionResult answerInquiry(String inqueryId,String answer)   // answer a query about tender
        {
            DBContext.GetInstance().answerInqiry(inqueryId,answer);
            return Json(null, JsonRequestBehavior.AllowGet);    //  allow ajax
        }
        public ActionResult TenderWinner(String tenderID,String acceptedbidder,String notice)   //  organization selects a winner
        {
            DBContext.GetInstance().updateWinningBid(tenderID,acceptedbidder,notice);
            return Json(null, JsonRequestBehavior.AllowGet);    //  allow ajax
        }
        public ActionResult takeAllInquries(String tenderId)    //  Take all inquiries about a tender
        {
            List<InquiryModel> inq =DBContext.GetInstance().findInquries(tenderId);
            return Json(inq, JsonRequestBehavior.AllowGet); //  allow ajax
        }
	}
}

OTMS/Views/Bidder/BidDashboard.cshtml
@model OTMS.Models.TenderNoticeModel
@{
    ViewBag.Title = "BidDashboard";
    List<OTMS.Models.NotificationModel> notilist = (List<OTMS.Models.NotificationModel>)ViewData["notifications"];
}
<br /><br />
    <h3>@Session["user"]'s Dashboard</h3>

<div class="btn-group show-on-hover">
    <a href="#" class="btn btn-info">Notifications (@notilist.Count)</a>
    <a aria-expanded="true" href="#" class="btn btn-info dropdown-toggle" data-toggle="dropdown"><span class="caret"></span></a>
    <ul class="dropdown-menu">

@foreach (OTMS.Models.NotificationModel noti in (List<OTMS.Models.NotificationModel>)ViewData["notifications"])
                            {

        <li><a href="#" onclick="notification('@noti.NotificationId')">@noti.NotificationText</a></li>

}
    </ul>
</div><br /><br />
    <div class="container-fluid">
        <div class="row-fluid">



            <div class="col-md-3" style="background-color: #dedef8;">
                <!--Sidebar content-->
                <div class="row">
              
                        <div class="col-lg-12" style="padding-top: 15px; overflow-y: scroll; height: 500px;">

                            @foreach (OTMS.Models.TenderNoticeModel temp in (List<OTMS.Models.TenderNoticeModel>)ViewData["tenders"])
                            {
                                TimeSpan differnce = temp.ExpDateTime - DateTime.Now;
                                <div class="panel panel-info">
                                    <div class="panel-heading" id="@temp.NoticeId">
                                        <h3 class="panel-title">Notice no @temp.NoticeId</h3>
                                    </div>
                                    <div class="panel-body">
                                        <p class="text-info">Type           : @temp.FieldName</p>
                                        <p class="text-info">Organization   : @temp.Organization</p>
                                        <p class="text-info">Remaining Days : @String.Format("{0:N2}", differnce.TotalDays);</p>

                                        <div class="btn-group btn-group-justified">
                                            <a href="#" class="btn btn-default" onclick="compDetails('@temp.Organization')">Info</a>
                                            <a href="#" class="btn btn-default" onclick="loadpdf('@temp.NoticeId')">PDF</a>
                                            <a href="#" class="btn btn-default" data-whatever="@temp.NoticeId" data-toggle="modal" data-target="#exampleModal">Ask</a>
                                        </div>

                                        <div class="btn-group btn-group-justified">
                                            <a href="#" class="btn btn-default" onclick="info('@temp.NoticeId')">Inquiries</a>
                                            <a href="#" class="btn btn-default" onclick="bid('@temp.NoticeId')">Bid</a>
                                           
                                        </div>
                                    </div>
                                </div>
                            }
                        </div>
              
                </div>
            </div>

            <div class="col-md-1" ></div>

            <div class="col-md-8" style="background-color: #dedef8;">
                <!--Body content-->
                <div class="row-fluid" id="Details">
                    
                    <label class="col-lg-2 control-label">Company :</label>
                    <label class="col-lg-10 control-label" style="color:blue" id="Company"></label>  
                    <label class="col-lg-2 control-label">Address :</label>
                    <label class="col-lg-10 control-label" style="color:blue" id="Address"></label>  
                    <label class="col-lg-2 control-label">TP      :</label>
                    <label class="col-lg-10 control-label" style="color:blue" id="TP"></label>
                    <label class="col-lg-2 control-label">Email   :</label>
                    <label class="col-lg-10 control-label" style="color:blue" id="Email"></label>
                    <label class="col-lg-2 control-label">Web     :</label>
                    <label class="col-lg-10 control-label" style="color:blue" id="Web"></label>
                    </div>
                <div class="row-fluid">
                   
                    <iframe src="" width="700" height="490" id="pdf"></iframe>

                </div>
                <div id="inquiry">
                    
                </div>
        
            </div>
</div>
</div>




<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="exampleModalLabel">New Inquiry about tender </h4><h4 id="modal_notice_id"></h4>
                                                                                                 </div>
            <div class="modal-body">
                <form>

                    <div class="form-group">
                        <label for="message-text" class="control-label">Question:</label>
                        <textarea class="form-control" id="message-text" required maxlength="400"></textarea>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" id="suubmit" class="btn btn-primary">Post inquiry</button>
            </div>
        </div>
    </div>
</div>


<script type="text/javascript">


    

    $('#suubmit').on('click', function (evt) {
        var message = $('#message-text').val();
        var noticeId = $('#modal_notice_id').text();

        if (message === "") { return false; } else {
            $.getJSON("@Url.Action("addNewInquiry", "Tender", new { noticeId="_noticeId", Question = "_question" })".replace("_noticeId", noticeId).replace("_question", message), function (data) {
            });

            $.getJSON("@Url.Action("CreateType1Notification", "Notification", new { tenderId = "_tenderId"})".replace("_tenderId", noticeId), function (data) {
            });

            $('#exampleModal').modal('hide');
        }
    });

    $('#exampleModal').on('show.bs.modal', function (event) {
        var button = $(event.relatedTarget) 
        var NoticeId = button.data('whatever') 
        $('#modal_notice_id').text(NoticeId);

    })

    document.addEventListener('DOMContentLoaded', function () {
        $('#pdf').hide();
        $('#Details').hide();
    }, false);

    function bid(val)
    {
        window.location.href = '/Bid/AddNewBid/' + val;
    }

    function compDetails(val) {
        $('#inquiry').hide();
        $('#pdf').hide();
        $('#Details').show(1000);
        var items = [];
        $.getJSON("@Url.Action("getAllOrganizations", "Organization", new { OrgUserName = "_OrgUserName" })".replace("_OrgUserName",val), function (data) {
            $.each(data, function (key, val) {

                $("#Company").html(val.Name);
                $("#Address").html(val.Address);
                $("#TP").html(val.TPNo);
                $("#Email").html(val.Email);
                $("#Web").html(val.Web);
            });
        });
    }

    function loadpdf(val)
    {
        $('#inquiry').hide();
        $('#Details').hide();
        $('#pdf').show(1000);
        var iframe = $('#pdf');
        iframe.attr('src', "@Url.Action("getPDFofNotice", "Tender", new { noticeID = "temp" })".replace("temp", val));
        console.log(val);
    }


    function info(val) {
        $('#Details').hide();
        $('#pdf').hide();
        $('#inquiry').show(1000);
        var items = [];
        $.getJSON("@Url.Action("takeAllInquries", "Tender", new { tenderId = "_tenderId" })".replace("_tenderId", val), function (data) {
            $.each(data, function (key, val) {
                if (val.Answer != "") {
                    items.push(
                        "<label class='col-lg-2 control-label'>" + "Question :" + "</label>" +
                        "<label class='col-lg-10 control-label' style='color:blue'>" + val.Question + "</label>" +
                        "<label class='col-lg-2 control-label'>Answer :</label>" +
                        "<label class='col-lg-10 control-label' style='color:blue'>" + val.Answer + "</label>"
                        );
                }
            });
            $("#inquiry").html(items.join(""));
        });
    }  
    function notification(val)
    {
        $.getJSON("@Url.Action("caughtNotification", "Notification", new { notificationID = "_notiId" })".replace("_notiId", val), function (data) {
        });
    }
</script>

OTMS/Views/Bidder/Bidderlogin.cshtml
@{
    ViewBag.Title = "Bidderlogin";
}

<h2>Bidder login</h2>


<br />
<div class="row">
    <div class="col-lg-6 col-lg-offset-3">
        <div class="well bs-component">
            <form class="form-horizontal" name="registerForm" action="@Url.Action("Bidderlogin", "Bidder")" method="POST" enctype="multipart/form-data">
                <fieldset>
                    <legend>Bidder Login</legend>

                    <div class="form-group">
                        <label for="inputName" class="col-lg-2 control-label"> User Name</label>
                        <div class="col-lg-10">
                            <input type="text" class="form-control" name="username" placeholder="User Name">
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="inputPassword" class="col-lg-2 control-label">Password</label>
                        <div class="col-lg-10">
                            <input type="password" class="form-control" name="password">
                        </div>
                    </div>
                    <label style="color:red" class="col-lg-12 control-label">@ViewData["errorMsg"]</label>
                    <div class="form-group">
                        <div class="col-lg-2 col-lg-offset-2">
                            <button type="submit" class="btn btn-primary">Login</button>
                        </div>
                    </div>


                </fieldset>
            </form>
        </div>
    </div>
</div>