OTMS/Controllers/BidController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OTMS.Models;
namespace OTMS.Controllers
{
    public class BidController : Controller
    {
        //
        // GET: /Bid/
        public ActionResult Index()
        {
            return View();
        }
       
        public ActionResult AddBid() 
        {   //  create a new bid 
            if (Request.HttpMethod.Equals("POST"))
            {
                   BidModel bid = new BidModel();
                   bid.Owner = (String)Session["username"];
                   bid.NoticeId = int.Parse(Request.Form["noticeid"]);
                   HttpPostedFileBase file = Request.Files["PDF"];

                if (file != null && file.ContentLength > 0)     //  upload PDF document
                {
                    System.IO.Stream fileStream = file.InputStream;
                    byte[] data = new byte[file.ContentLength];
                    fileStream.Read(data, 0, data.Length);
                    fileStream.Close();
                    bid.PdfDoc = data;
                }

                DBContext.GetInstance().CreateNewBid(bid);
                return RedirectToAction("BidDashboard", "Bidder"); 
            }
            return RedirectToAction("BidDashboard", "Bidder");   //  return to dashboard after creating it.
        }
        public ActionResult AddNewBid(String noticeId) 
        {
            if (Session["isOrg"] != null)   //  if not in a session 
            {
                if (!(bool)Session["isOrg"]) //  If bidders session
                {
                    ViewData["noticeId"] = noticeId;
                    return View();  //  return correct view
                }
            }
            return null;    // do nothing
        }
	}
}

OTMS/Views/Bid/AddNewBid.cshtml
@{
    ViewBag.Title = "AddNewBid";
}
<br /><br />
<h2>Add New Bid</h2>
<br />
<div class="row">
    <div class="col-lg-6 col-lg-offset-3">
        <div class="well bs-component">
            <form class="form-horizontal" name="NewBid" action="@Url.Action("AddBid", "Bid")" method="POST" enctype="multipart/form-data">
                <fieldset>
                    <legend>Upload your Bid</legend>

                    <div class="form-group">
                        <label for="TenderId" class="col-lg-2 control-label">Tender ID</label>
                        <div class="col-lg-10">
                            <input type="text" class="form-control" name="noticeid" value="@ViewData["noticeId"]" readonly="readonly">
                        </div>
                    </div>

                    <label for="PDF" class="col-lg-2 control-label">Bid (PDF)</label>
                    <div class="col-lg-10">
                        <input id="pdfInput" type="file" accept=".pdf" name="PDF"><br />
                    </div>                 

                    <div class="form-group">
                        <div class="col-lg-10 col-lg-offset-2">
                            <button type="reset" class="btn btn-default">Cancel</button>
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    </div>


                </fieldset>
            </form>
        </div>
    </div>
</div>